server:
  port: 9090
spring:
    datasource:
        name: local
        url: jdbc:mysql://127.0.0.1:3306/wristband?characterEncoding=UTF-8&&serverTimezone=UTC
        #url: jdbc:mysql://192.168.199.161:3306/changh?characterEncoding=UTF-8&&serverTimezone=UTC
        #url: jdbc:mysql://frpgz1.idcfengye.com:10005/changh?characterEncoding=UTF-8&&serverTimezone=UTC
        username: root
        #password: WSNwsn?b407407
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver #必须是这个
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  config-location: classpath:mybatis-config.xml # mybatis配置文件所
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.bookcycle.pojo  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql